services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: couponsphere-jenkins
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/project-repo
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    user: root # Needed to access docker socket
    networks:
      - couponsphere-network

volumes:
  jenkins_home:

networks:
  couponsphere-network:
    name: create-a-full-stack-industry-grade_couponsphere-network
    external: true
